
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.webservice.weather.ws;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-10-23T19:51:29.211+08:00
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "WeatherWebService",
                      portName = "WeatherWebServiceSoap12",
                      targetNamespace = "http://WebXml.com.cn/",
                      wsdlLocation = "file:/c:/aaa.xml",
                      endpointInterface = "com.webservice.weather.ws.WeatherWebServiceSoap")
                      
public class WeatherWebServiceSoap12Impl implements WeatherWebServiceSoap {

    private static final Logger LOG = Logger.getLogger(WeatherWebServiceSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see com.webservice.weather.ws.WeatherWebServiceSoap#getSupportProvince()*
     */
    public com.webservice.weather.ws.ArrayOfString getSupportProvince() { 
        LOG.info("Executing operation getSupportProvince");
        try {
            com.webservice.weather.ws.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.weather.ws.WeatherWebServiceSoap#getWeatherbyCityNamePro(java.lang.String theCityName, java.lang.String theUserID)*
     */
    public com.webservice.weather.ws.ArrayOfString getWeatherbyCityNamePro(java.lang.String theCityName, java.lang.String theUserID) { 
        LOG.info("Executing operation getWeatherbyCityNamePro");
        System.out.println(theCityName);
        System.out.println(theUserID);
        try {
            com.webservice.weather.ws.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.weather.ws.WeatherWebServiceSoap#getSupportCity(java.lang.String byProvinceName)*
     */
    public com.webservice.weather.ws.ArrayOfString getSupportCity(java.lang.String byProvinceName) { 
        LOG.info("Executing operation getSupportCity");
        System.out.println(byProvinceName);
        try {
            com.webservice.weather.ws.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.weather.ws.WeatherWebServiceSoap#getSupportDataSet()*
     */
    public com.webservice.weather.ws.GetSupportDataSetResponse.GetSupportDataSetResult getSupportDataSet() { 
        LOG.info("Executing operation getSupportDataSet");
        try {
            com.webservice.weather.ws.GetSupportDataSetResponse.GetSupportDataSetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.weather.ws.WeatherWebServiceSoap#getWeatherbyCityName(java.lang.String theCityName)*
     */
    public com.webservice.weather.ws.ArrayOfString getWeatherbyCityName(java.lang.String theCityName) { 
        LOG.info("Executing operation getWeatherbyCityName");
        System.out.println(theCityName);
        try {
            com.webservice.weather.ws.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
