
package com.webservice.ny.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-04-09T13:03:40.537+08:00
 * Generated source version: 3.1.11
 * 
 */
 
public class SaveYCJCServicePortType_SaveYCJCServiceHttpPort_Server{

    protected SaveYCJCServicePortType_SaveYCJCServiceHttpPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SaveYCJCServiceHttpPortImpl();
        String address = "http://211.142.202.28:7013/nysanitate/services/SaveYCJCService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SaveYCJCServicePortType_SaveYCJCServiceHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
