package com.webservice.ayhx.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-01T22:08:16.980+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://service.tblycjc.webservice.client.dekn.com.cn", name = "SaveYCJCServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SaveYCJCServicePortType {

    @WebResult(name = "out", targetNamespace = "http://service.tblycjc.webservice.client.dekn.com.cn")
    @RequestWrapper(localName = "saveYCJC", targetNamespace = "http://service.tblycjc.webservice.client.dekn.com.cn", className = "com.my.hxwebservice.SaveYCJC")
    @WebMethod
    @ResponseWrapper(localName = "saveYCJCResponse", targetNamespace = "http://service.tblycjc.webservice.client.dekn.com.cn", className = "com.my.hxwebservice.SaveYCJCResponse")
    public java.lang.String saveYCJC(
        @WebParam(name = "in0", targetNamespace = "http://service.tblycjc.webservice.client.dekn.com.cn")
        java.lang.String in0
    ) throws DataAccessException_Exception;
}
