
package com.webservice.kfyz.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-08-15T14:51:09.828+08:00
 * Generated source version: 3.3.1
 *
 */

public class YCSaveDBHttpPost_YCSaveDBHttpPost_Server{

    protected YCSaveDBHttpPost_YCSaveDBHttpPost_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new YCSaveDBHttpPostImpl();
        String address = "CHANGE_ME";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new YCSaveDBHttpPost_YCSaveDBHttpPost_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
