
package com.webservice.kfyz.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-08-15T14:51:09.838+08:00
 * Generated source version: 3.3.1
 *
 */

public class YCSaveDBHttpGet_YCSaveDBHttpGet_Server{

    protected YCSaveDBHttpGet_YCSaveDBHttpGet_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new YCSaveDBHttpGetImpl();
        String address = "http://47.100.108.91/SaveDB/YCSaveDB.asmx";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new YCSaveDBHttpGet_YCSaveDBHttpGet_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
