package com.webservice.kfyz.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-08-15T14:51:09.828+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "YCSaveDBSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface YCSaveDBSoap {

    @WebMethod(operationName = "UpdateStates", action = "http://tempuri.org/UpdateStates")
    @RequestWrapper(localName = "UpdateStates", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.UpdateStates")
    @ResponseWrapper(localName = "UpdateStatesResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.UpdateStatesResponse")
    @WebResult(name = "UpdateStatesResult", targetNamespace = "http://tempuri.org/")
    public boolean updateStates();

    @WebMethod(operationName = "UpdateYCRealData", action = "http://tempuri.org/UpdateYCRealData")
    @RequestWrapper(localName = "UpdateYCRealData", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.UpdateYCRealData")
    @ResponseWrapper(localName = "UpdateYCRealDataResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.UpdateYCRealDataResponse")
    @WebResult(name = "UpdateYCRealDataResult", targetNamespace = "http://tempuri.org/")
    public boolean updateYCRealData(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "datas", targetNamespace = "http://tempuri.org/")
        java.lang.String datas
    );

    @WebMethod(operationName = "GetProjectList", action = "http://tempuri.org/GetProjectList")
    @RequestWrapper(localName = "GetProjectList", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.GetProjectList")
    @ResponseWrapper(localName = "GetProjectListResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.GetProjectListResponse")
    @WebResult(name = "GetProjectListResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getProjectList(
        @WebParam(name = "uName", targetNamespace = "http://tempuri.org/")
        java.lang.String uName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "usersId", targetNamespace = "http://tempuri.org/")
        int usersId,
        @WebParam(name = "proName", targetNamespace = "http://tempuri.org/")
        java.lang.String proName
    );

    @WebMethod(operationName = "UpdateRealtimeData", action = "http://tempuri.org/UpdateRealtimeData")
    @RequestWrapper(localName = "UpdateRealtimeData", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.UpdateRealtimeData")
    @ResponseWrapper(localName = "UpdateRealtimeDataResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.UpdateRealtimeDataResponse")
    @WebResult(name = "UpdateRealtimeDataResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String updateRealtimeData(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "datas", targetNamespace = "http://tempuri.org/")
        java.lang.String datas
    );

    @WebMethod(operationName = "GetTransferJson", action = "http://tempuri.org/GetTransferJson")
    @RequestWrapper(localName = "GetTransferJson", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.GetTransferJson")
    @ResponseWrapper(localName = "GetTransferJsonResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.GetTransferJsonResponse")
    @WebResult(name = "GetTransferJsonResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getTransferJson();

    @WebMethod(operationName = "GetAppVersion", action = "http://tempuri.org/GetAppVersion")
    @RequestWrapper(localName = "GetAppVersion", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.GetAppVersion")
    @ResponseWrapper(localName = "GetAppVersionResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.GetAppVersionResponse")
    @WebResult(name = "GetAppVersionResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getAppVersion(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    @WebMethod(operationName = "GetYCPH", action = "http://tempuri.org/GetYCPH")
    @RequestWrapper(localName = "GetYCPH", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.GetYCPH")
    @ResponseWrapper(localName = "GetYCPHResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.GetYCPHResponse")
    @WebResult(name = "GetYCPHResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getYCPH(
        @WebParam(name = "uName", targetNamespace = "http://tempuri.org/")
        java.lang.String uName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "usersId", targetNamespace = "http://tempuri.org/")
        int usersId,
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        int page,
        @WebParam(name = "size", targetNamespace = "http://tempuri.org/")
        int size,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        java.lang.String type
    );

    @WebMethod(operationName = "CheckUsers", action = "http://tempuri.org/CheckUsers")
    @RequestWrapper(localName = "CheckUsers", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.CheckUsers")
    @ResponseWrapper(localName = "CheckUsersResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.CheckUsersResponse")
    @WebResult(name = "CheckUsersResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String checkUsers(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String userPassword
    );

    @WebMethod(operationName = "GetProjectDetails", action = "http://tempuri.org/GetProjectDetails")
    @RequestWrapper(localName = "GetProjectDetails", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.GetProjectDetails")
    @ResponseWrapper(localName = "GetProjectDetailsResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.GetProjectDetailsResponse")
    @WebResult(name = "GetProjectDetailsResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getProjectDetails(
        @WebParam(name = "uName", targetNamespace = "http://tempuri.org/")
        java.lang.String uName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "projectId", targetNamespace = "http://tempuri.org/")
        int projectId,
        @WebParam(name = "SN", targetNamespace = "http://tempuri.org/")
        java.lang.String sn
    );

    @WebMethod(operationName = "GetYCCurve", action = "http://tempuri.org/GetYCCurve")
    @RequestWrapper(localName = "GetYCCurve", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.GetYCCurve")
    @ResponseWrapper(localName = "GetYCCurveResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.GetYCCurveResponse")
    @WebResult(name = "GetYCCurveResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getYCCurve(
        @WebParam(name = "uName", targetNamespace = "http://tempuri.org/")
        java.lang.String uName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "ycparamId", targetNamespace = "http://tempuri.org/")
        int ycparamId,
        @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
        java.lang.String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        java.lang.String endDate
    );

    @WebMethod(operationName = "UpdateYCRealtimeData", action = "http://tempuri.org/UpdateYCRealtimeData")
    @RequestWrapper(localName = "UpdateYCRealtimeData", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.UpdateYCRealtimeData")
    @ResponseWrapper(localName = "UpdateYCRealtimeDataResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.UpdateYCRealtimeDataResponse")
    @WebResult(name = "UpdateYCRealtimeDataResult", targetNamespace = "http://tempuri.org/")
    public boolean updateYCRealtimeData(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "datas", targetNamespace = "http://tempuri.org/")
        java.lang.String datas
    );

    @WebMethod(operationName = "GetYCWX", action = "http://tempuri.org/GetYCWX")
    @RequestWrapper(localName = "GetYCWX", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.GetYCWX")
    @ResponseWrapper(localName = "GetYCWXResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.kfyz.ws.GetYCWXResponse")
    @WebResult(name = "GetYCWXResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getYCWX(
        @WebParam(name = "uName", targetNamespace = "http://tempuri.org/")
        java.lang.String uName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "usersId", targetNamespace = "http://tempuri.org/")
        int usersId,
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        int page,
        @WebParam(name = "size", targetNamespace = "http://tempuri.org/")
        int size
    );
}
