package com.webservice.kfyz.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-08-15T14:51:09.828+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "YCSaveDBHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface YCSaveDBHttpGet {

    @WebMethod(operationName = "UpdateStates")
    @WebResult(name = "boolean", targetNamespace = "http://tempuri.org/", partName = "Body")
    public boolean updateStates();

    @WebMethod(operationName = "UpdateYCRealData")
    @WebResult(name = "boolean", targetNamespace = "http://tempuri.org/", partName = "Body")
    public boolean updateYCRealData(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "datas", name = "datas", targetNamespace = "http://tempuri.org/")
        java.lang.String datas
    );

    @WebMethod(operationName = "GetProjectList")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getProjectList(
        @WebParam(partName = "uName", name = "uName", targetNamespace = "http://tempuri.org/")
        java.lang.String uName,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(partName = "usersId", name = "usersId", targetNamespace = "http://tempuri.org/")
        java.lang.String usersId,
        @WebParam(partName = "proName", name = "proName", targetNamespace = "http://tempuri.org/")
        java.lang.String proName
    );

    @WebMethod(operationName = "UpdateRealtimeData")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String updateRealtimeData(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "datas", name = "datas", targetNamespace = "http://tempuri.org/")
        java.lang.String datas
    );

    @WebMethod(operationName = "GetTransferJson")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getTransferJson();

    @WebMethod(operationName = "GetAppVersion")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getAppVersion(
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    @WebMethod(operationName = "GetYCPH")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getYCPH(
        @WebParam(partName = "uName", name = "uName", targetNamespace = "http://tempuri.org/")
        java.lang.String uName,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(partName = "usersId", name = "usersId", targetNamespace = "http://tempuri.org/")
        java.lang.String usersId,
        @WebParam(partName = "page", name = "page", targetNamespace = "http://tempuri.org/")
        java.lang.String page,
        @WebParam(partName = "size", name = "size", targetNamespace = "http://tempuri.org/")
        java.lang.String size,
        @WebParam(partName = "type", name = "type", targetNamespace = "http://tempuri.org/")
        java.lang.String type
    );

    @WebMethod(operationName = "CheckUsers")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String checkUsers(
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String userPassword
    );

    @WebMethod(operationName = "GetProjectDetails")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getProjectDetails(
        @WebParam(partName = "uName", name = "uName", targetNamespace = "http://tempuri.org/")
        java.lang.String uName,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(partName = "projectId", name = "projectId", targetNamespace = "http://tempuri.org/")
        java.lang.String projectId,
        @WebParam(partName = "SN", name = "SN", targetNamespace = "http://tempuri.org/")
        java.lang.String sn
    );

    @WebMethod(operationName = "GetYCCurve")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getYCCurve(
        @WebParam(partName = "uName", name = "uName", targetNamespace = "http://tempuri.org/")
        java.lang.String uName,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(partName = "ycparamId", name = "ycparamId", targetNamespace = "http://tempuri.org/")
        java.lang.String ycparamId,
        @WebParam(partName = "startDate", name = "startDate", targetNamespace = "http://tempuri.org/")
        java.lang.String startDate,
        @WebParam(partName = "endDate", name = "endDate", targetNamespace = "http://tempuri.org/")
        java.lang.String endDate
    );

    @WebMethod(operationName = "UpdateYCRealtimeData")
    @WebResult(name = "boolean", targetNamespace = "http://tempuri.org/", partName = "Body")
    public boolean updateYCRealtimeData(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "datas", name = "datas", targetNamespace = "http://tempuri.org/")
        java.lang.String datas
    );

    @WebMethod(operationName = "GetYCWX")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getYCWX(
        @WebParam(partName = "uName", name = "uName", targetNamespace = "http://tempuri.org/")
        java.lang.String uName,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(partName = "usersId", name = "usersId", targetNamespace = "http://tempuri.org/")
        java.lang.String usersId,
        @WebParam(partName = "page", name = "page", targetNamespace = "http://tempuri.org/")
        java.lang.String page,
        @WebParam(partName = "size", name = "size", targetNamespace = "http://tempuri.org/")
        java.lang.String size
    );
}
