package com.webservice.kfyz.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-08-15T14:51:09.838+08:00
 * Generated source version: 3.3.1
 *
 */
@WebServiceClient(name = "YCSaveDB",
                  wsdlLocation = "http://47.100.108.91/SaveDB/YCSaveDB.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class YCSaveDB extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "YCSaveDB");
    public final static QName YCSaveDBHttpPost = new QName("http://tempuri.org/", "YCSaveDBHttpPost");
    public final static QName YCSaveDBSoap12 = new QName("http://tempuri.org/", "YCSaveDBSoap12");
    public final static QName YCSaveDBSoap = new QName("http://tempuri.org/", "YCSaveDBSoap");
    public final static QName YCSaveDBHttpGet = new QName("http://tempuri.org/", "YCSaveDBHttpGet");
    static {
        URL url = null;
        try {
            url = new URL("http://47.100.108.91/SaveDB/YCSaveDB.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(YCSaveDB.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://47.100.108.91/SaveDB/YCSaveDB.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public YCSaveDB(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public YCSaveDB(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YCSaveDB() {
        super(WSDL_LOCATION, SERVICE);
    }

    public YCSaveDB(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public YCSaveDB(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public YCSaveDB(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns YCSaveDBHttpPost
     */
    @WebEndpoint(name = "YCSaveDBHttpPost")
    public YCSaveDBHttpPost getYCSaveDBHttpPost() {
        return super.getPort(YCSaveDBHttpPost, YCSaveDBHttpPost.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YCSaveDBHttpPost
     */
    @WebEndpoint(name = "YCSaveDBHttpPost")
    public YCSaveDBHttpPost getYCSaveDBHttpPost(WebServiceFeature... features) {
        return super.getPort(YCSaveDBHttpPost, YCSaveDBHttpPost.class, features);
    }


    /**
     *
     * @return
     *     returns YCSaveDBSoap
     */
    @WebEndpoint(name = "YCSaveDBSoap12")
    public YCSaveDBSoap getYCSaveDBSoap12() {
        return super.getPort(YCSaveDBSoap12, YCSaveDBSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YCSaveDBSoap
     */
    @WebEndpoint(name = "YCSaveDBSoap12")
    public YCSaveDBSoap getYCSaveDBSoap12(WebServiceFeature... features) {
        return super.getPort(YCSaveDBSoap12, YCSaveDBSoap.class, features);
    }


    /**
     *
     * @return
     *     returns YCSaveDBSoap
     */
    @WebEndpoint(name = "YCSaveDBSoap")
    public YCSaveDBSoap getYCSaveDBSoap() {
        return super.getPort(YCSaveDBSoap, YCSaveDBSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YCSaveDBSoap
     */
    @WebEndpoint(name = "YCSaveDBSoap")
    public YCSaveDBSoap getYCSaveDBSoap(WebServiceFeature... features) {
        return super.getPort(YCSaveDBSoap, YCSaveDBSoap.class, features);
    }


    /**
     *
     * @return
     *     returns YCSaveDBHttpGet
     */
    @WebEndpoint(name = "YCSaveDBHttpGet")
    public YCSaveDBHttpGet getYCSaveDBHttpGet() {
        return super.getPort(YCSaveDBHttpGet, YCSaveDBHttpGet.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YCSaveDBHttpGet
     */
    @WebEndpoint(name = "YCSaveDBHttpGet")
    public YCSaveDBHttpGet getYCSaveDBHttpGet(WebServiceFeature... features) {
        return super.getPort(YCSaveDBHttpGet, YCSaveDBHttpGet.class, features);
    }

}
