
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.webservice.kfyz.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-08-15T14:51:09.808+08:00
 * Generated source version: 3.3.1
 *
 */

@javax.jws.WebService(
                      serviceName = "YCSaveDB",
                      portName = "YCSaveDBHttpGet",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://47.100.108.91/SaveDB/YCSaveDB.asmx?wsdl",
                      endpointInterface = "com.webservice.kfyz.ws.YCSaveDBHttpGet")

public class YCSaveDBHttpGetImpl implements YCSaveDBHttpGet {

    private static final Logger LOG = Logger.getLogger(YCSaveDBHttpGetImpl.class.getName());

    /* (non-Javadoc)
     * @see com.webservice.kfyz.ws.YCSaveDBHttpGet#updateStates()*
     */
    public boolean updateStates() {
        LOG.info("Executing operation updateStates");
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.kfyz.ws.YCSaveDBHttpGet#updateYCRealData(java.lang.String sn, java.lang.String datas)*
     */
    public boolean updateYCRealData(java.lang.String sn, java.lang.String datas) {
        LOG.info("Executing operation updateYCRealData");
        System.out.println(sn);
        System.out.println(datas);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.kfyz.ws.YCSaveDBHttpGet#getProjectList(java.lang.String uName, java.lang.String password, java.lang.String usersId, java.lang.String proName)*
     */
    public java.lang.String getProjectList(java.lang.String uName, java.lang.String password, java.lang.String usersId, java.lang.String proName) {
        LOG.info("Executing operation getProjectList");
        System.out.println(uName);
        System.out.println(password);
        System.out.println(usersId);
        System.out.println(proName);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.kfyz.ws.YCSaveDBHttpGet#updateRealtimeData(java.lang.String sn, java.lang.String datas)*
     */
    public java.lang.String updateRealtimeData(java.lang.String sn, java.lang.String datas) {
        LOG.info("Executing operation updateRealtimeData");
        System.out.println(sn);
        System.out.println(datas);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.kfyz.ws.YCSaveDBHttpGet#getTransferJson()*
     */
    public java.lang.String getTransferJson() {
        LOG.info("Executing operation getTransferJson");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.kfyz.ws.YCSaveDBHttpGet#getAppVersion(java.lang.String userName, java.lang.String password)*
     */
    public java.lang.String getAppVersion(java.lang.String userName, java.lang.String password) {
        LOG.info("Executing operation getAppVersion");
        System.out.println(userName);
        System.out.println(password);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.kfyz.ws.YCSaveDBHttpGet#getYCPH(java.lang.String uName, java.lang.String password, java.lang.String usersId, java.lang.String page, java.lang.String size, java.lang.String type)*
     */
    public java.lang.String getYCPH(java.lang.String uName, java.lang.String password, java.lang.String usersId, java.lang.String page, java.lang.String size, java.lang.String type) {
        LOG.info("Executing operation getYCPH");
        System.out.println(uName);
        System.out.println(password);
        System.out.println(usersId);
        System.out.println(page);
        System.out.println(size);
        System.out.println(type);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.kfyz.ws.YCSaveDBHttpGet#checkUsers(java.lang.String userName, java.lang.String userPassword)*
     */
    public java.lang.String checkUsers(java.lang.String userName, java.lang.String userPassword) {
        LOG.info("Executing operation checkUsers");
        System.out.println(userName);
        System.out.println(userPassword);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.kfyz.ws.YCSaveDBHttpGet#getProjectDetails(java.lang.String uName, java.lang.String password, java.lang.String projectId, java.lang.String sn)*
     */
    public java.lang.String getProjectDetails(java.lang.String uName, java.lang.String password, java.lang.String projectId, java.lang.String sn) {
        LOG.info("Executing operation getProjectDetails");
        System.out.println(uName);
        System.out.println(password);
        System.out.println(projectId);
        System.out.println(sn);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.kfyz.ws.YCSaveDBHttpGet#getYCCurve(java.lang.String uName, java.lang.String password, java.lang.String ycparamId, java.lang.String startDate, java.lang.String endDate)*
     */
    public java.lang.String getYCCurve(java.lang.String uName, java.lang.String password, java.lang.String ycparamId, java.lang.String startDate, java.lang.String endDate) {
        LOG.info("Executing operation getYCCurve");
        System.out.println(uName);
        System.out.println(password);
        System.out.println(ycparamId);
        System.out.println(startDate);
        System.out.println(endDate);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.kfyz.ws.YCSaveDBHttpGet#updateYCRealtimeData(java.lang.String sn, java.lang.String datas)*
     */
    public boolean updateYCRealtimeData(java.lang.String sn, java.lang.String datas) {
        LOG.info("Executing operation updateYCRealtimeData");
        System.out.println(sn);
        System.out.println(datas);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.webservice.kfyz.ws.YCSaveDBHttpGet#getYCWX(java.lang.String uName, java.lang.String password, java.lang.String usersId, java.lang.String page, java.lang.String size)*
     */
    public java.lang.String getYCWX(java.lang.String uName, java.lang.String password, java.lang.String usersId, java.lang.String page, java.lang.String size) {
        LOG.info("Executing operation getYCWX");
        System.out.println(uName);
        System.out.println(password);
        System.out.println(usersId);
        System.out.println(page);
        System.out.println(size);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
