
package com.webservice.yc.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-07-17T11:51:11.250+08:00
 * Generated source version: 3.1.11
 * 
 */
public final class JKInfoSoap_JKInfoSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "JKInfo");

    private JKInfoSoap_JKInfoSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = JKInfo.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        JKInfo ss = new JKInfo(wsdlURL, SERVICE_NAME);
        JKInfoSoap port = ss.getJKInfoSoap12();  
        
        {
        System.out.println("Invoking xhtTJDateRec...");
        java.lang.String _xhtTJDateRec_mKeyPwd = "";
        java.lang.String _xhtTJDateRec_mJsonStr = "";
        java.lang.String _xhtTJDateRec__return = port.xhtTJDateRec(_xhtTJDateRec_mKeyPwd, _xhtTJDateRec_mJsonStr);
        System.out.println("xhtTJDateRec.result=" + _xhtTJDateRec__return);


        }
        {
        System.out.println("Invoking xhtKQDateRec...");
        java.lang.String _xhtKQDateRec_mKeyPwd = "";
        java.lang.String _xhtKQDateRec_mJsonStr = "";
        java.lang.String _xhtKQDateRec__return = port.xhtKQDateRec(_xhtKQDateRec_mKeyPwd, _xhtKQDateRec_mJsonStr);
        System.out.println("xhtKQDateRec.result=" + _xhtKQDateRec__return);


        }
        {
        System.out.println("Invoking xhtSJJDateRec...");
        java.lang.String _xhtSJJDateRec_mKeyPwd = "";
        java.lang.String _xhtSJJDateRec_mJsonStr = "";
        java.lang.String _xhtSJJDateRec__return = port.xhtSJJDateRec(_xhtSJJDateRec_mKeyPwd, _xhtSJJDateRec_mJsonStr);
        System.out.println("xhtSJJDateRec.result=" + _xhtSJJDateRec__return);


        }
        {
        System.out.println("Invoking xhtYCDateRec...");
        java.lang.String _xhtYCDateRec_mKeyPwd = "";
        java.lang.String _xhtYCDateRec_mJsonStr = "";
        java.lang.String _xhtYCDateRec__return = port.xhtYCDateRec(_xhtYCDateRec_mKeyPwd, _xhtYCDateRec_mJsonStr);
        System.out.println("xhtYCDateRec.result=" + _xhtYCDateRec__return);


        }

        System.exit(0);
    }

}
