
package com.webservice.yc.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-07-17T11:51:11.328+08:00
 * Generated source version: 3.1.11
 * 
 */
 
public class JKInfoSoap_JKInfoSoap_Server{

    protected JKInfoSoap_JKInfoSoap_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new JKInfoSoapImpl();
        String address = "http://42.63.25.70:9000/yczj/webservice/jkinfo.asmx";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new JKInfoSoap_JKInfoSoap_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
