package com.webservice.yc.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-07-17T11:51:11.328+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "JKInfoSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface JKInfoSoap {

    /**
     * 塔机监控数据接收接口
     */
    @WebMethod(operationName = "Xht_TJDateRec", action = "http://tempuri.org/Xht_TJDateRec")
    @RequestWrapper(localName = "Xht_TJDateRec", targetNamespace = "http://tempuri.org/", className = "com.webservice.yc.XhtTJDateRec")
    @ResponseWrapper(localName = "Xht_TJDateRecResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.yc.XhtTJDateRecResponse")
    @WebResult(name = "Xht_TJDateRecResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String xhtTJDateRec(
        @WebParam(name = "mKeyPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String mKeyPwd,
        @WebParam(name = "mJsonStr", targetNamespace = "http://tempuri.org/")
        java.lang.String mJsonStr
    );

    /**
     * 工地考勤数据接收接口
     */
    @WebMethod(operationName = "Xht_KQDateRec", action = "http://tempuri.org/Xht_KQDateRec")
    @RequestWrapper(localName = "Xht_KQDateRec", targetNamespace = "http://tempuri.org/", className = "com.webservice.yc.XhtKQDateRec")
    @ResponseWrapper(localName = "Xht_KQDateRecResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.yc.XhtKQDateRecResponse")
    @WebResult(name = "Xht_KQDateRecResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String xhtKQDateRec(
        @WebParam(name = "mKeyPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String mKeyPwd,
        @WebParam(name = "mJsonStr", targetNamespace = "http://tempuri.org/")
        java.lang.String mJsonStr
    );

    /**
     * 升降机监控数据接收接�?
     */
    @WebMethod(operationName = "Xht_SJJDateRec", action = "http://tempuri.org/Xht_SJJDateRec")
    @RequestWrapper(localName = "Xht_SJJDateRec", targetNamespace = "http://tempuri.org/", className = "com.webservice.yc.XhtSJJDateRec")
    @ResponseWrapper(localName = "Xht_SJJDateRecResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.yc.XhtSJJDateRecResponse")
    @WebResult(name = "Xht_SJJDateRecResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String xhtSJJDateRec(
        @WebParam(name = "mKeyPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String mKeyPwd,
        @WebParam(name = "mJsonStr", targetNamespace = "http://tempuri.org/")
        java.lang.String mJsonStr
    );

    /**
     * 扬尘监控数据接收接口
     */
    @WebMethod(operationName = "Xht_YCDateRec", action = "http://tempuri.org/Xht_YCDateRec")
    @RequestWrapper(localName = "Xht_YCDateRec", targetNamespace = "http://tempuri.org/", className = "com.webservice.yc.XhtYCDateRec")
    @ResponseWrapper(localName = "Xht_YCDateRecResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.yc.XhtYCDateRecResponse")
    @WebResult(name = "Xht_YCDateRecResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String xhtYCDateRec(
        @WebParam(name = "mKeyPwd", targetNamespace = "http://tempuri.org/")
        java.lang.String mKeyPwd,
        @WebParam(name = "mJsonStr", targetNamespace = "http://tempuri.org/")
        java.lang.String mJsonStr
    );
}
