package com.webservice.yc.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-07-17T11:51:11.343+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "JKInfo", 
                  wsdlLocation = "http://42.63.25.70:9000/yczj/webservice/jkinfo.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class JKInfo extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "JKInfo");
    public final static QName JKInfoSoap12 = new QName("http://tempuri.org/", "JKInfoSoap12");
    public final static QName JKInfoSoap = new QName("http://tempuri.org/", "JKInfoSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://42.63.25.70:9000/yczj/webservice/jkinfo.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JKInfo.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://42.63.25.70:9000/yczj/webservice/jkinfo.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public JKInfo(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JKInfo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JKInfo() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public JKInfo(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public JKInfo(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public JKInfo(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns JKInfoSoap
     */
    @WebEndpoint(name = "JKInfoSoap12")
    public JKInfoSoap getJKInfoSoap12() {
        return super.getPort(JKInfoSoap12, JKInfoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JKInfoSoap
     */
    @WebEndpoint(name = "JKInfoSoap12")
    public JKInfoSoap getJKInfoSoap12(WebServiceFeature... features) {
        return super.getPort(JKInfoSoap12, JKInfoSoap.class, features);
    }


    /**
     *
     * @return
     *     returns JKInfoSoap
     */
    @WebEndpoint(name = "JKInfoSoap")
    public JKInfoSoap getJKInfoSoap() {
        return super.getPort(JKInfoSoap, JKInfoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JKInfoSoap
     */
    @WebEndpoint(name = "JKInfoSoap")
    public JKInfoSoap getJKInfoSoap(WebServiceFeature... features) {
        return super.getPort(JKInfoSoap, JKInfoSoap.class, features);
    }

}
