package com.webservice.lyln.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-09-02T11:23:33.125+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "DustSurveillanceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface DustSurveillanceSoap {

    @WebMethod(operationName = "UploadDustInfo", action = "http://tempuri.org/UploadDustInfo")
    @RequestWrapper(localName = "UploadDustInfo", targetNamespace = "http://tempuri.org/", className = "com.webservice.lyln.ws.UploadDustInfo")
    @ResponseWrapper(localName = "UploadDustInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.webservice.lyln.ws.UploadDustInfoResponse")
    @WebResult(name = "UploadDustInfoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String uploadDustInfo(
        @WebParam(name = "sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign,
        @WebParam(name = "unitno", targetNamespace = "http://tempuri.org/")
        java.lang.String unitno,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content
    );
}
