
package com.webservice.lyln.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-09-02T11:23:33.107+08:00
 * Generated source version: 3.3.1
 *
 */
public final class DustSurveillanceSoap_DustSurveillanceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "DustSurveillance");

    private DustSurveillanceSoap_DustSurveillanceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DustSurveillance.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        DustSurveillance ss = new DustSurveillance(wsdlURL, SERVICE_NAME);
        DustSurveillanceSoap port = ss.getDustSurveillanceSoap12();

        {
        System.out.println("Invoking uploadDustInfo...");
        java.lang.String _uploadDustInfo_sign = "";
        java.lang.String _uploadDustInfo_unitno = "";
        java.lang.String _uploadDustInfo_content = "";
        java.lang.String _uploadDustInfo__return = port.uploadDustInfo(_uploadDustInfo_sign, _uploadDustInfo_unitno, _uploadDustInfo_content);
        System.out.println("uploadDustInfo.result=" + _uploadDustInfo__return);


        }

        System.exit(0);
    }

}
