
package com.webservice.xxxq.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-22T09:45:04.397+08:00
 * Generated source version: 3.3.1
 *
 */
public final class YCJKServiceSoap_YCJKServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "YCJKService");

    private YCJKServiceSoap_YCJKServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = YCJKService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        YCJKService ss = new YCJKService(wsdlURL, SERVICE_NAME);
        YCJKServiceSoap port = ss.getYCJKServiceSoap12();

        {
        System.out.println("Invoking saveYCJC...");
        java.lang.String _saveYCJC_elements = "";
        java.lang.String _saveYCJC__return = port.saveYCJC(_saveYCJC_elements);
        System.out.println("saveYCJC.result=" + _saveYCJC__return);


        }
        {
        System.out.println("Invoking saveYCJCArray...");
        com.webservice.xxxq.ws.ArrayOfArrayOfString _saveYCJCArray_elements = null;
        java.lang.String _saveYCJCArray__return = port.saveYCJCArray(_saveYCJCArray_elements);
        System.out.println("saveYCJCArray.result=" + _saveYCJCArray__return);


        }

        System.exit(0);
    }

}
