
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.webservice.xxxq.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-22T09:45:04.424+08:00
 * Generated source version: 3.3.1
 *
 */

@javax.jws.WebService(
                      serviceName = "YCJKService",
                      portName = "YCJKServiceHttpPost",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://xxxq.jyvjd.com/PM25/wservices/YCJKService.asmx?wsdl",
                      endpointInterface = "com.webservice.xxxq.ws.YCJKServiceHttpPost")

public class YCJKServiceHttpPostImpl implements YCJKServiceHttpPost {

    private static final Logger LOG = Logger.getLogger(YCJKServiceHttpPostImpl.class.getName());

    /* (non-Javadoc)
     * @see com.webservice.xxxq.ws.YCJKServiceHttpPost#saveYCJC(java.lang.String elements)*
     */
    public java.lang.String saveYCJC(java.lang.String elements) {
        LOG.info("Executing operation saveYCJC");
        System.out.println(elements);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
