
package com.webservice.pds.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-05-30T17:29:59.037+08:00
 * Generated source version: 3.3.1
 */

@WebFault(name = "DataAccessException", targetNamespace = "http://service.tblycjc.webservice.client.dekn.com.cn")
public class DataAccessException_Exception extends Exception {

    private com.webservice.pds.ws.DataAccessException dataAccessException;

    public DataAccessException_Exception() {
        super();
    }

    public DataAccessException_Exception(String message) {
        super(message);
    }

    public DataAccessException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DataAccessException_Exception(String message, com.webservice.pds.ws.DataAccessException dataAccessException) {
        super(message);
        this.dataAccessException = dataAccessException;
    }

    public DataAccessException_Exception(String message, com.webservice.pds.ws.DataAccessException dataAccessException, java.lang.Throwable cause) {
        super(message, cause);
        this.dataAccessException = dataAccessException;
    }

    public com.webservice.pds.ws.DataAccessException getFaultInfo() {
        return this.dataAccessException;
    }
}
