
package com.webservice.pds.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-05-30T17:29:59.027+08:00
 * Generated source version: 3.3.1
 *
 */
public final class SaveYCJCServicePortType_SaveYCJCServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.tblycjc.webservice.client.dekn.com.cn", "SaveYCJCService");

    private SaveYCJCServicePortType_SaveYCJCServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SaveYCJCService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SaveYCJCService ss = new SaveYCJCService(wsdlURL, SERVICE_NAME);
        SaveYCJCServicePortType port = ss.getSaveYCJCServiceHttpPort();

        {
        System.out.println("Invoking saveYCJC...");
        java.lang.String _saveYCJC_in0 = "";
        try {
            java.lang.String _saveYCJC__return = port.saveYCJC(_saveYCJC_in0);
            System.out.println("saveYCJC.result=" + _saveYCJC__return);

        } catch (DataAccessException_Exception e) {
            System.out.println("Expected exception: DataAccessException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
